### ISSUE TITLE
--invert and --both options to ruler

### ISSUE THREAD

**Issue by stevengj** [NanoComp/photonics-opt-testbed#36]
Right now, `ruler` measures the lengthscales only of the "black" region, i.e. the "minimum linewidth".

It would be good to have an option, maybe `--invert`, that automatically inverts the image (swaps black and white) to measure the lengthscale of the "white" region, i.e. the "minimum linespacing".

And along with that we could have a `--both` option for it to run both cases and report the smaller of the two numbers.

cc @mawc2019

**Comment by mawc2019** [comment]
These options are added in PR https://github.com/NanoComp/photonics-opt-testbed/pull/40. The tutorial will also be updated.
