### ISSUE TITLE
Clean up the ruler module and bring it out of a prototype state

### ISSUE THREAD

**Issue by ianwilliamson** [NanoComp/photonics-opt-testbed#38]
The `ruler` module should be cleaned up and reorganized in order to improve its usability.

- [x] Migrate the ruler module to its own separately maintained repository; it is a standalone function that does not rely on the data and simulation scripts that live in this repository. Moving the ruler to its own repository would allow it to be pip-installable and to be correctly imported by other modules (e.g. the different scripts in this repo).
- [x] Add full doc strings and usage examples for public, user-facing function(s)
- [x] Add type hints to function inputs / outputs
- [x] Mark private functions as such by prefixing them with "_"
- [x] Add a few units tests, with inline hardcoded arrays, that validate the correctness of the ruler

**Comment by stevengj** [comment]
One unit test would be to write a function that generates "rounded rectangle" images, similar to the example in the paper, with an arbitrary resolution and rotation angle, and check that it gives (roughly) the same answer regardless of resolution (sufficiently high), rotation angle, or whether the image is inverted (for open–close).

**Comment by mawc2019** [comment]
> Add type hints to function inputs / outputs

Shall we add type hints only for user-facing functions or for all functions? In addition, the most important user-facing function, i.e., `minimum_length`, has varying output types that depend on users' choices. Shall we omit the output type hints?

> We could also have a few "hard-coded" tests for simple structures, similar to what Wenchao used when debugging.

These tests are in the [notebook](https://github.com/NanoComp/photonics-opt-testbed/blob/main/ruler/example.ipynb), but the structures are not "hard-coded", but generated by a few lines of code.

> One unit test would be to write a function that generates "rounded rectangle" images, similar to the example in the paper, with an arbitrary resolution and rotation angle, and check that it gives (roughly) the same answer regardless of resolution (sufficiently high), rotation angle, or whether the image is inverted (for open–close).

Some tests with different resolutions are as follows.

Resolution = 25:
![image](https://user-images.githubusercontent.com/60903466/217303433-266c6453-98ac-4e97-8bdf-5edda29effdf.png)

Resolution = 50:
![image](https://user-images.githubusercontent.com/60903466/217303511-c029d4b2-390c-4da9-8b33-f42028279330.png)

Resolution = 100:
![image](https://user-images.githubusercontent.com/60903466/217303549-40ee38ef-5ac0-42d4-81b5-1fb8c01ef154.png)

**Comment by ianwilliamson** [comment]
> Shall we omit the output type hints?

It looks like `minimum_length()` returns a float or `None` - the way to type this is `Optional[float]`.

**Comment by mawc2019** [comment]
In my newest version that has not been pull into the master branch, `minimum_length()` can return one float number or two float numbers (when a user wants the minimum length scales of both solid and void regions). Is it still convenient to set a type hint?

**Comment by mawc2019** [comment]
Thanks to @mfschubert for sending me his test on [`metrics.py`](https://github.com/mfschubert/topology/blob/main/metrics.py). When applied to the rounded squares with random rotation angles, the comparison between `metrics.py` and `ruler.py` is as follows.
![image](https://user-images.githubusercontent.com/60903466/218466812-0a959129-eb63-4764-b738-0276fae7feb5.png)

When applied to the discs, the comparison between `metrics.py` and `ruler.py` is as follows.
![image](https://user-images.githubusercontent.com/60903466/218467125-b0b22c17-8b94-473e-88c8-867e445f138e.png)

When applied to the squares, the comparison between `metrics.py` and `ruler.py` is as follows.
![image](https://user-images.githubusercontent.com/60903466/218467296-9f152856-d7ff-4839-af37-c4632c49db87.png)

We can see that in most cases, `metrics.py` gives more accurate estimation. I previously thought the differences in outcomes were mainly due to the difference in calculating morphological operations, but I was wrong. Even if the morphological functions in `ruler.py` are replaced with their opencv counterparts, the outcomes of `ruler.py` do not change obviously.

Apart from the details of morphological operations, `ruler.py` calculates the difference between the morphological opening and closing, while `metric.py` calculates the difference between a pattern and its morphological opening. The two programs also count interior pixels in different ways, which should be the major reason for different outcomes.

**Comment by ianwilliamson** [comment]
> In my latest version that has not been pulled into the master branch, `minimum_length()` can return one float number or two float numbers (when a user wants the minimum length scales of both solid and void regions). Is it still convenient to set a type hint?

From an API design point of view, it's probably more reasonable to always return both numbers. The user can ignore one if they don't need it. An API whose number of return values varies is more complex to design around.

**Comment by mawc2019** [comment]
> From an API design point of view, it's probably more reasonable to always return both numbers.

It would also make the code more concise. However, in most cases, users may only want one number. Always calculating both numbers may not be necessary and may sound less efficient. Shall we sacrifice the efficiency?

**Comment by ianwilliamson** [comment]
> Always calculating both numbers may not be necessary and may sound less efficient. Shall we sacrifice the efficiency?

That's fair. Another option would be to always return a length-2 tuple but have the un-computed quantities be `None`.

**Comment by ianwilliamson** [comment]
Style guide: https://google.github.io/styleguide/pyguide.html
Python formatter: https://github.com/google/yapf (pip-installable)

**Comment by mawc2019** [comment]
In the latest version of `ruler.py` that has not been uploaded, the criterion for interior solid pixels has been changed to that in `metrics.py`. The tests [here](https://github.com/NanoComp/photonics-opt-testbed/issues/38#issuecomment-1428497893) now become:
![image](https://user-images.githubusercontent.com/60903466/221770004-e174b2e9-ad0a-4b32-b54e-b78a78b399b7.png)
![image](https://user-images.githubusercontent.com/60903466/221770080-7eb8fda2-d975-485c-821e-3c825a4036b2.png)
![image](https://user-images.githubusercontent.com/60903466/221770175-f804922d-4728-4b38-8f61-248262a0ccd7.png)

If the morphological functions in `ruler.py` are changed to their opencv counterparts, the results given by `ruler.py` and `metrics.py` will be the same, but `ruler.py` will lose its 3d functions although they do not affect this project.

**Comment by mawc2019** [comment]
> If the morphological functions in ruler.py are changed to their opencv counterparts, the results given by ruler.py and metrics.py will be the same, ……

This is not correct. Apart from the implementation of morphological functions and the criterion of non-interfacial solid pixels, final results are also influenced by details of binary search and shapes of kernels with various sizes. In `metrics.py`, the kernels are generated in an approach that involves `binary_opening`. At some diameters, the shapes of these filters are slightly different from those generated without `binary_opening`.
